# NUMPY

# Creating a NUMPY array

In [2]:
import numpy as np

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
type(a)

numpy.ndarray

In [13]:
b=np.array([1,2.5,'p',1+2j,True])
b

array(['1', '2.5', 'p', '(1+2j)', 'True'], dtype='<U64')

In [15]:
type(b)

numpy.ndarray

In [60]:
c= np.array([[1,2,3],[4,5,6]])   
c

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
d=np.array([[1,3,5],[5,7,9],[10,5,6]])
d

array([[ 1,  3,  5],
       [ 5,  7,  9],
       [10,  5,  6]])

# dtype

In [26]:
a

array([1, 2, 3])

In [28]:
a=np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [30]:
a1=np.array([[1,4,56],[75,20,1],[3,4,5]],dtype = float)
a1

array([[ 1.,  4., 56.],
       [75., 20.,  1.],
       [ 3.,  4.,  5.]])

In [34]:
a2=np.array([1,4,6],dtype=str)
a2

array(['1', '4', '6'], dtype='<U1')

In [36]:
a3=np.array([0,1,5],dtype=bool)
a3

array([False,  True,  True])

In [40]:
a4=np.array([7,3,9],dtype=complex)
a4

array([7.+0.j, 3.+0.j, 9.+0.j])

# arange

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [47]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [49]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# reshape

In [53]:
b1 = np.arange(10).reshape(5,2)
b1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
b2 = np.arange(12).reshape(4,3)
b2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
b3 = np.arange(0,9).reshape(3,3)
b3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [183]:
b4 = np.arange(10,19,dtype=float).reshape(3,3)
b4

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

# ones

In [67]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.ones((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [71]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [73]:
np.ones((4,2),complex)

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])

In [77]:
a = np.ones((1,3))
a

array([[1., 1., 1.]])

# zeros

In [85]:
np.zeros((4,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [89]:
np.zeros((3,2),dtype=bool)

array([[False, False],
       [False, False],
       [False, False]])

In [91]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# random

In [99]:
np.random.random(10)

array([0.36264026, 0.90469033, 0.90160109, 0.40906766, 0.01148492,
       0.18502642, 0.88449161, 0.08360807, 0.36687375, 0.6700353 ])

In [128]:
np.random.rand(3)

array([0.29446349, 0.73946765, 0.12188247])

In [126]:
np.random.rand(3,3)

array([[0.28674024, 0.39214872, 0.67477839],
       [0.48680056, 0.03293002, 0.9600511 ],
       [0.94239338, 0.21840655, 0.46323303]])

# randint

In [122]:
np.random.randint(5)

3

In [147]:
np.random.randint(1,10)             # prints some random value between 1 to 10

2

In [155]:
np.random.randint(10,50,5)          # prints some random values between 10 to 50 with 5 values

array([36, 41, 39, 32, 34])

In [161]:
np.random.randint(0,30,(4,3))        

array([[15,  9,  6],
       [ 7, 27, 29],
       [23, 20, 14],
       [11,  1, 25]])

In [167]:
np.random.randint(0,10,(2,2))

array([[4, 5],
       [1, 0]])

# identity

In [173]:
x = np.identity(2)
x

array([[1., 0.],
       [0., 1.]])

In [177]:
x1= np.identity(3,dtype=int)
x1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [179]:
x2= np.identity(6,dtype=int)
x2

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

# shape

In [186]:
x

array([[1., 0.],
       [0., 1.]])

In [188]:
x.shape

(2, 2)

In [190]:
x1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [192]:
x1.shape

(3, 3)

In [194]:
a

array([[1., 1., 1.]])

In [196]:
a.shape

(1, 3)

In [200]:
x3=np.arange(5)
x3

array([0, 1, 2, 3, 4])

In [202]:
x3.shape

(5,)

# size

In [209]:
b1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [211]:
b1.size

10

In [213]:
x3

array([0, 1, 2, 3, 4])

In [215]:
x3.size

5

In [217]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [219]:
c.size

6

In [221]:
c.dtype

dtype('int32')

In [223]:
x3.dtype

dtype('int32')

# astype

In [226]:
x3

array([0, 1, 2, 3, 4])

In [228]:
x3.astype(float)

array([0., 1., 2., 3., 4.])

In [230]:
a

array([[1., 1., 1.]])

In [234]:
a.astype(int)

array([[1, 1, 1]])

# array operations

In [237]:
z1 = np.arange(15).reshape(5,3)
z1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [245]:
z2 = np.random.randint(0,15,(5,3))
z2

array([[ 8, 13, 14],
       [14,  0, 13],
       [ 4,  6,  0],
       [ 3,  3,  3],
       [12, 10,  7]])

In [249]:
# arithmetic operator
z1+z2

array([[ 8, 14, 16],
       [17,  4, 18],
       [10, 13,  8],
       [12, 13, 14],
       [24, 23, 21]])

In [251]:
# substraction
z1-z2

array([[ -8, -12, -12],
       [-11,   4,  -8],
       [  2,   1,   8],
       [  6,   7,   8],
       [  0,   3,   7]])

In [253]:
z1*z2

array([[  0,  13,  28],
       [ 42,   0,  65],
       [ 24,  42,   0],
       [ 27,  30,  33],
       [144, 130,  98]])

In [260]:
z1**2

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])

In [264]:
z1%2

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]], dtype=int32)

# relational operator

In [267]:
z1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [269]:
z2

array([[ 8, 13, 14],
       [14,  0, 13],
       [ 4,  6,  0],
       [ 3,  3,  3],
       [12, 10,  7]])

In [271]:
z2<z1

array([[False, False, False],
       [False,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [273]:
z1<z2

array([[ True,  True,  True],
       [ True, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [275]:
z1!=z2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [277]:
z1<=z2

array([[ True,  True,  True],
       [ True, False,  True],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

In [279]:
z2>=z1

array([[ True,  True,  True],
       [ True, False,  True],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

# round

In [289]:
arr = np.array([1.5,7.8,9.1])
arr

array([1.5, 7.8, 9.1])

In [327]:
np.round(arr)

array([2., 8., 9.])

In [329]:
arr1 = np.array([1.2,2.3,4.4])
np.round(arr1)

array([1., 2., 4.])

# floor

In [304]:
arr

array([1.5, 7.8, 9.1])

In [310]:
np.floor(arr)

array([1., 7., 9.])

In [312]:
arr1

array([1.2, 2.3, 4.4])

In [314]:
np.floor(arr1)

array([1., 2., 4.])

# ceil

In [317]:
arr

array([1.5, 7.8, 9.1])

In [319]:
np.ceil(arr)

array([ 2.,  8., 10.])

In [323]:
arr1

array([1.2, 2.3, 4.4])

In [325]:
np.ceil(arr1)

array([2., 3., 5.])

# indexing & slicing

In [339]:
arr_1 = np.arange(16)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [341]:
arr_1[0]

0

In [343]:
arr_1[5]

5

In [345]:
arr_1[:6]

array([0, 1, 2, 3, 4, 5])

In [347]:
arr_2=np.arange(100).reshape(10,10)
arr_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [349]:
arr_2[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [351]:
arr_2[:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [355]:
arr_2[1:-3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [357]:
arr_2[-1,-5]

95

In [359]:
arr_2[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [361]:
arr_2[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [365]:
arr_2[::2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [367]:
arr_2[-5,3]

53

In [369]:
arr_2[7,-4]

76

In [371]:
arr_2[0:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [373]:
arr_2[0,-4]

6

In [377]:
arr_2[0,5]

5

In [379]:
arr_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [381]:
arr_2[5:9,3:6]

array([[53, 54, 55],
       [63, 64, 65],
       [73, 74, 75],
       [83, 84, 85]])

In [383]:
arr_2[4:5,5:6]

array([[45]])

In [385]:
arr_2[9:10,1:2]

array([[91]])

In [387]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [393]:
# iterating on array
for i in arr_1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [395]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [397]:
arr_1.mean()

7.5

In [399]:
arr_1.min()

0

In [401]:
arr_1.max()

15

In [406]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [412]:
arr_1.reshape(4,4,order='C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [416]:
arr_1.reshape(4,4,order='F')

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [422]:
mat = np.arange(100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [424]:
row = 2

In [426]:
col = 5

In [428]:
mat[row:col]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [430]:
mat[row:10]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [432]:
mat[col,-1]

59

In [434]:
mat[row:3,col:6]

array([[25]])

In [436]:
mat[row,col]

25

In [438]:
mat[col,row]

52

# masking

In [441]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [443]:
mat<row

array([[ True,  True, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [445]:
mat>col

array([[False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [447]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [449]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [451]:
mat!=50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [453]:
mat<60

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [455]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [457]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [459]:
mat[mat>60]

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [461]:
mat[mat!=70]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [463]:
mat>=50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [465]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [467]:
mat<=30

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [469]:
mat[mat<=30]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])